GET  http://localhost:7777/food

####

POST http://localhost:7777/addFood
Content-Type: application/json

{
    "img": "https://p0.pxfuel.com/preview/501/238/477/fruit-eating-dessert-healthy.jpg",
    "title": "Uva",
    "description": "Alimentare contenente fruttosio",
    "tipo": "frutto"
}

####

PATCH  http://localhost:7777/changeFood/661fdaffd3955c2c8f72f6df
Content-Type: application/json

{
    "tipo": "Primo"
}

####

DELETE http://localhost:7777/removeFood/
