GET  http://localhost:7777/food

####

POST http://localhost:7777/addFood
Content-Type: application/json

{
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgeeQI22-FZdznTm97eOhCWjcpvKx6_eA7A50Eivu-5Q&s",
    "title": "Mela Verde",
    "description": "ricco di vitamina C",
    "tipo": "frutto"
}

####

PATCH  http://localhost:7777/changeFood/661fdaffd3955c2c8f72f6df
Content-Type: application/json

{
    "tipo": "Primo"
}

####

DELETE http://localhost:7777/removeFood/
