GET  http://localhost:7777/food

####

POST http://localhost:7777/addFood
Content-Type: application/json

{
    "img": "https://p0.pxfuel.com/preview/501/238/477/fruit-eating-dessert-healthy.jpg",
    "title": "Uva",
    "description": "Alimentare contenente fruttosio",
    "tipo": "frutta"
}

####

PATCH  http://localhost:7777/changeFood/663268edc22868d1da0e374c
Content-Type: application/json

{
    "description": "Lattuga romana, pomodori e salsa Caesar"
}

####

DELETE http://localhost:7777/removeFood/66326a97c22868d1da0e3758
