GET http://localhost:7777/users

####

GET http://localhost:7777/users/inserisciid


####

PATCH  http://localhost:7777/users/661f05ac7fdba54b8d7a2f3c
Content-Type: application/json

{
    "nome": ""
}
####

DELETE  http://localhost:7777/users/6620028460f4717897a81b37


####
POST http://localhost:7777/addUsers
Content-Type: application/json

{
    "nome": "Mauro",
    "email": "mauro@gmail.com",
    "password": "ciao1234"
}