GET http://localhost:7777/users

####

GET http://localhost:7777/users/66251c3dda7d4a8bf1080d28


####

PATCH  http://localhost:7777/users/661f05ac7fdba54b8d7a2f3c
Content-Type: application/json

{
    "nome": ""
}
####

DELETE  http://localhost:7777/users/6626908e4bb8f9a7a020700e


####
POST http://localhost:7777/addUsers
Content-Type: application/json

{
    "nome": "Mauro",
    "email": "Mauro@gmail.com",
    "password": "mauro"
}